# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46baede6cfbaaa595c4af3d7e07d2df795a21c6254d9474a930a88d8f16fdd1ef5ff9135a458ae3149e87a02a3ebc3cc646785028e14a9bdb7b4d0be61d0a447

test:
  secret_key_base: a63449b5735fb0de669b435acab0a56953e38d8e7889de737894a957266021d24e8c4cb7943e2b2e1499b92989f495602d7573ad007a605d4f6270d008d24b6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
